# Generated by Django 4.1.7 on 2024-02-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDITIONAL_EARNINGS',
            fields=[
                ('AddtlEarning_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('COLA_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_HISTORY',
            fields=[
                ('History_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
                ('IN_OUT', models.CharField(max_length=255)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('CA_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CA_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COLA',
            fields=[
                ('COLA_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COLA_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COOP',
            fields=[
                ('COOP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COOP_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Last_name', models.CharField(max_length=255)),
                ('First_name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Join_Date', models.DateField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField()),
                ('Email', models.CharField(max_length=255)),
                ('BankNumber', models.IntegerField()),
                ('Salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HDMF',
            fields=[
                ('HDMF_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Employer_Rate', models.FloatField()),
                ('Employee_Rate', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HMO',
            fields=[
                ('HMO_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('HMO_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HOLIDAY',
            fields=[
                ('Holiday_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhilHealth',
            fields=[
                ('PhilHealth_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Employer_Rate', models.FloatField()),
                ('Employee_Rate', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('SSS_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Regular_SS_Employer_Rate', models.FloatField()),
                ('Regular_SS_Employee_Rate', models.FloatField()),
                ('EC_Contribution', models.FloatField()),
                ('WISP_Employer_Rate', models.FloatField()),
                ('WISP_Employee_Rate', models.FloatField()),
                ('Type', models.CharField(max_length=255)),
                ('Total_Contribution', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UNIFORMLAPTOPDEDUCTIONS',
            fields=[
                ('ULDeductions_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('ULDeductions_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WitholdingTax',
            fields=[
                ('WTAX_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Fix_Tax_Amount', models.FloatField()),
                ('Tax_Rate_On_Excess', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payslip_Transaction',
            fields=[
                ('Transaction_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Distributed', models.DateField(blank=True, null=True)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Net_Pay', models.FloatField()),
                ('Absence_Deductions', models.FloatField()),
                ('AddtlEarning_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.additional_earnings')),
                ('CA_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.ca')),
                ('COLA_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.cola')),
                ('COOP_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.coop')),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('HDMF_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.hdmf')),
                ('HMO_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.hmo')),
                ('PhilHealth_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.philhealth')),
                ('SSS_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.sss')),
                ('ULDeductions_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.uniformlaptopdeductions')),
                ('WTAX_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.witholdingtax')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('Leave_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Leaves_Left', models.IntegerField()),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_RECORD',
            fields=[
                ('Attendance_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
                ('IN_OUT', models.CharField(max_length=255)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('History_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.attendance_history')),
            ],
        ),
        migrations.AddField(
            model_name='attendance_history',
            name='Employee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee'),
        ),
        migrations.AddField(
            model_name='attendance_history',
            name='Holiday_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.holiday'),
        ),
        migrations.AddField(
            model_name='attendance_history',
            name='Leave_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.leave'),
        ),
        migrations.AddField(
            model_name='attendance_history',
            name='Transaction_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.payslip_transaction'),
        ),
    ]
