from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Employee)
admin.site.register(HMO)
admin.site.register(UNIFORMLAPTOPDEDUCTIONS)
admin.site.register(CA)
admin.site.register(COOP)
admin.site.register(COLA)
admin.site.register(ADDITIONAL_EARNINGS)
admin.site.register(HOLIDAY)
admin.site.register(Leave)
admin.site.register(SSS)
admin.site.register(PhilHealth)
admin.site.register(HDMF)
admin.site.register(WitholdingTax)
admin.site.register(Payslip_Transaction)
admin.site.register(ATTENDANCE_HISTORY)
admin.site.register(USER_ACCOUNT)
admin.site.register(Department)
admin.site.register(BANK_FILES)
admin.site.register(File)