# Generated by Django 5.0.3 on 2024-04-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDITIONAL_EARNINGS',
            fields=[
                ('AddtlEarning_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('ADD_EARNINGS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BANK_FILES',
            fields=[
                ('BANK_ENTRY_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('BANK_FILE_NAME', models.CharField(max_length=250)),
                ('PAYROLL_PERIOD', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('CA_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CA_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COLA',
            fields=[
                ('COLA_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COLA_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COOP',
            fields=[
                ('COOP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COOP_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Last_name', models.CharField(max_length=255)),
                ('First_name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Join_Date', models.DateField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField()),
                ('Email', models.CharField(max_length=255)),
                ('BankNumber', models.IntegerField()),
                ('Salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HDMF',
            fields=[
                ('HDMF_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Employer_Rate', models.FloatField()),
                ('Employee_Rate', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HMO',
            fields=[
                ('HMO_ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('HMO_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HOLIDAY',
            fields=[
                ('Holiday_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhilHealth',
            fields=[
                ('PhilHealth_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Employer_Rate', models.FloatField()),
                ('Employee_Rate', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('SSS_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Regular_SS_Employer_Rate', models.FloatField()),
                ('Regular_SS_Employee_Rate', models.FloatField()),
                ('EC_Contribution', models.FloatField()),
                ('WISP_Employer_Rate', models.FloatField()),
                ('WISP_Employee_Rate', models.FloatField()),
                ('Total_Contribution', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UNIFORMLAPTOPDEDUCTIONS',
            fields=[
                ('ULDeductions_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('ULDeductions_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='USER_ACCOUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WitholdingTax',
            fields=[
                ('WTAX_Rate_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Fix_Tax_Amount', models.FloatField()),
                ('Tax_Rate_On_Excess', models.FloatField()),
                ('Start_Range', models.FloatField()),
                ('End_Range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('Leave_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Leaves_Left', models.IntegerField()),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_HISTORY',
            fields=[
                ('History_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TimeIn', models.TimeField(blank=True, null=True)),
                ('TimeOut', models.TimeField(blank=True, null=True)),
                ('TimeIn_2', models.TimeField(blank=True, null=True)),
                ('TimeOut_2', models.TimeField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('OT', models.FloatField()),
                ('HoursWorked', models.FloatField()),
                ('Employee_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('Holiday_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.holiday')),
                ('Leave_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.leave')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip_Transaction',
            fields=[
                ('Transaction_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Distributed', models.DateField(blank=True, null=True)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Net_Pay', models.FloatField()),
                ('Total_Deductions', models.FloatField()),
                ('Absence_Deductions', models.FloatField()),
                ('OT', models.FloatField()),
                ('Holiday_Comp', models.FloatField()),
                ('SSS_Rate_ID', models.FloatField()),
                ('PhilHealth_Rate_ID', models.FloatField()),
                ('HDMF_Rate_ID', models.FloatField()),
                ('WTAX_Rate_ID', models.FloatField()),
                ('HMO_Rate_ID', models.FloatField()),
                ('AddtlEarning_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.additional_earnings')),
                ('CA_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.ca')),
                ('COLA_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.cola')),
                ('COOP_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.coop')),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee')),
                ('ULDeductions_Rate_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrollapp.uniformlaptopdeductions')),
            ],
        ),
    ]
