# Generated by Django 4.1.7 on 2024-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('id_number', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=300)),
                ('Department', models.CharField(max_length=300)),
                ('Role', models.CharField(max_length=300)),
                ('Join_Date', models.DateField(blank=True, null=True)),
                ('Phone_Number', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('BankNumber', models.CharField(max_length=300)),
                ('Salary', models.FloatField()),
                ('ColaEarnings', models.FloatField()),
                ('CAdeductions', models.FloatField()),
                ('COOPdeductions', models.FloatField()),
                ('ULdeductions', models.FloatField()),
            ],
        ),
    ]
