# Generated by Django 4.1.7 on 2024-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Name',
        ),
        migrations.AddField(
            model_name='employee',
            name='First_name',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Last_name',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Middle_name',
            field=models.CharField(default='e', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='BankNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=6),
        ),
    ]
