# Generated by Django 5.0.3 on 2024-04-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_history',
            name='Employee_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.employee'),
        ),
        migrations.AddField(
            model_name='payslip_transaction',
            name='Holiday_Comp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip_transaction',
            name='OT',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='Holiday_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.holiday'),
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='Leave_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.leave'),
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='TimeIn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='TimeIn_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='TimeOut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='TimeOut_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip_transaction',
            name='HDMF_Rate_ID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip_transaction',
            name='HMO_Rate_ID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip_transaction',
            name='PhilHealth_Rate_ID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip_transaction',
            name='SSS_Rate_ID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payslip_transaction',
            name='WTAX_Rate_ID',
            field=models.FloatField(),
        ),
    ]
