# Generated by Django 5.0.3 on 2024-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0003_alter_employee_banknumber_alter_employee_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
