# Generated by Django 5.0.3 on 2024-05-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0005_file_alter_employee_banknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='End_Date',
        ),
    ]
