# Generated by Django 5.0.3 on 2024-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0006_remove_leave_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='Leaves_Left',
        ),
        migrations.AddField(
            model_name='employee',
            name='Sick_Leaves',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Vacation_Leaves',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
