# Generated by Django 5.0.3 on 2024-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0007_remove_leave_leaves_left_employee_sick_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmo',
            name='HMO_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
