# Generated by Django 5.0.3 on 2024-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0008_alter_hmo_hmo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmo',
            name='HMO_ID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
