# Generated by Django 5.0.3 on 2024-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0009_alter_hmo_hmo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmo',
            name='HMO_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
