# Generated by Django 5.0.3 on 2024-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0012_payslip_transaction_nightshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_files',
            name='BANK_FILE',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
    ]
