# Generated by Django 5.0.3 on 2024-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0013_bank_files_bank_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_history',
            name='NightShift_applied',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendance_history',
            name='OT_applied',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
