# Generated by Django 5.0.3 on 2024-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0014_attendance_history_nightshift_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_files',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
