# Generated by Django 5.0.3 on 2024-05-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0015_bank_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_files',
            name='Date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
