# Generated by Django 5.0.3 on 2024-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0016_alter_bank_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='BankNumber',
            field=models.CharField(max_length=255),
        ),
    ]
