# Generated by Django 5.0.3 on 2024-05-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0017_alter_employee_banknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='First_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
