# Generated by Django 5.0.3 on 2024-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0018_alter_employee_first_name_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_earnings',
            name='AddtlEarning_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance_history',
            name='History_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bank_files',
            name='BANK_ENTRY_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ca',
            name='CA_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cola',
            name='COLA_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coop',
            name='COOP_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hmo',
            name='HMO_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='Holiday_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Leave_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payslip_transaction',
            name='Transaction_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uniformlaptopdeductions',
            name='ULDeductions_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
