# Generated by Django 5.0.3 on 2024-05-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0019_alter_additional_earnings_addtlearning_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmo',
            name='HMO_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
